#!/bin/sh

if [ -z "$AOC_SESSION" ]; then
	echo "AOC_SESSION env variable not found."
	exit 1
fi

DAY=$(printf "%02d" ${1:-$(date +"%-d")})
YEAR=$(printf "%04d" ${2:-$(date +"%Y")})
echo "Getting $YEAR/$DAY > $DAY.txt"
curl -b "session=$AOC_SESSION" -A "https://github.com/llyyr" https://adventofcode.com/$YEAR/day/$DAY/input > $DAY.txt
